# Generated by Django 4.0.6 on 2022-07-21 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impersonalaccount',
            name='code',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='impersonalaccount',
            name='parent_ac',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.impersonalaccount'),
        ),
        migrations.AlterField(
            model_name='impersonalaccount',
            name='type_ac',
            field=models.CharField(choices=[('AS', 'Asset'), ('LI', 'Liability'), ('IN', 'Income'), ('EX', 'Expense')], max_length=2),
        ),
    ]
