# Generated by Django 4.0.6 on 2022-07-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_impersonalaccount_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impersonalaccount',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
