# Generated by Django 4.0.6 on 2022-07-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_impersonalaccount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impersonalaccount',
            name='type_ac',
            field=models.CharField(blank=True, choices=[('AS', 'Asset'), ('LI', 'Liability'), ('IN', 'Income'), ('EX', 'Expense')], max_length=2),
        ),
    ]
