# Generated by Django 4.0.6 on 2022-07-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='journals.transaction'),
        ),
    ]
