# Generated by Django 4.0.6 on 2022-07-21 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_impersonalaccount_code_and_more'),
        ('journals', '0003_split_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.impersonalaccount'),
        ),
        migrations.AlterField(
            model_name='split',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journals.transaction'),
        ),
        migrations.AlterField(
            model_name='split',
            name='type_split',
            field=models.CharField(choices=[('dr', 'Debit'), ('dr', 'Credit')], max_length=2),
        ),
    ]
