# Generated by Django 4.0.6 on 2022-07-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_alter_split_account_alter_split_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='type_split',
            field=models.CharField(choices=[('dr', 'Debit'), ('cr', 'Credit')], max_length=2),
        ),
    ]
